const data = [
  {
    attr_id: 301,
    nfp_2018: 1,
    usda_tag:  'CA',
    name:  'Calcium',
    unit: 'mg',
  },
  {
    attr_id: 205,
    nfp_2018: 1,
    usda_tag: 'CHOCDF',
    name: 'Carbohydrate, by difference',
    unit: 'g',
  },
  {
    attr_id: 601,
    nfp_2018: 1,
    usda_tag: 'CHOLE',
    name: 'Cholesterol',
    unit: 'mg',
  },
  {
    attr_id: 208,
    nfp_2018: 1,
    usda_tag: 'ENERC_KCAL',
    name: 'Calories',
    unit: 'kcal',
  },
  {
    attr_id: 606,
    nfp_2018: 1,
    usda_tag: 'FASAT',
    name: 'Fatty acids, total saturated',
    unit: 'g',
  },
  {
    attr_id: 204,
    nfp_2018: 1,
    usda_tag: 'FAT',
    name: 'Total lipid (fat)',
    unit: 'g',
  },
  {
    attr_id: 605,
    nfp_2018: 1,
    usda_tag: 'FATRN',
    name: 'Fatty acids, total trans',
    unit: 'g',
  },
  {
    attr_id: 303,
    nfp_2018: 1,
    usda_tag: 'FE',
    name: 'Iron, Fe',
    unit: 'mg',
  },
  {
    attr_id: 291,
    nfp_2018: 1,
    usda_tag: 'FIBTG',
    name: 'Fiber, total dietary',
    unit: 'g',
  },
  {
    attr_id: 306,
    nfp_2018: 1,
    usda_tag: 'K',
    name: 'Potassium',
    unit: 'mg',
  },
  {
    attr_id: 307,
    nfp_2018: 1,
    usda_tag: 'NA',
    name: 'Sodium',
    unit: 'mg',
  },
  {
    attr_id: 203,
    nfp_2018: 1,
    usda_tag: 'PROCNT',
    name: 'Protein',
    unit: 'g',
  },
  {
    attr_id: 269,
    nfp_2018: 1,
    usda_tag: 'SUGAR',
    name: 'Sugars, total',
    unit: 'g',
  },
  {
    attr_id: 539,
    nfp_2018: 1,
    usda_tag: 'SUGAR_ADD',
    name: 'Sugars, added',
    unit: 'g',
  },
  {
    attr_id: 324,
    nfp_2018: 1,
    usda_tag: 'VITD',
    name: 'Vitamin D',
    unit: 'IU',
  },
  {
    attr_id: 513,
    nfp_2018: 0,
    usda_tag: 'ALA_G',
    name: 'Alanine',
    unit: 'g',
  },
  {
    attr_id: 221,
    nfp_2018: 0,
    usda_tag: 'ALC',
    name: 'Alcohol, ethyl',
    unit: 'g',
  },
  {
    attr_id: 511,
    nfp_2018: 0,
    usda_tag: 'ARG_G',
    name: 'Arginine',
    unit: 'g',
  },
  {
    attr_id: 207,
    nfp_2018: 0,
    usda_tag: 'ASH',
    name: 'Ash',
    unit: 'g',
  },
  {
    attr_id: 514,
    nfp_2018: 0,
    usda_tag: 'ASP_G',
    name: 'Aspartic acid',
    unit: 'g',
  },
  {
    attr_id: 454,
    nfp_2018: 0,
    usda_tag: 'BETN',
    name: 'Betaine',
    unit: 'mg',
  },
  {
    attr_id: 262,
    nfp_2018: 0,
    usda_tag: 'CAFFN',
    name: 'Caffeine',
    unit: 'mg',
  },
  {
    attr_id: 639,
    nfp_2018: 0,
    usda_tag: 'CAMD5',
    name: 'Campesterol',
    unit: 'mg',
  },
  {
    attr_id: 322,
    nfp_2018: 0,
    usda_tag: 'CARTA',
    name: 'Carotene, alpha',
    unit: 'Âµg',
  },
  {
    attr_id: 321,
    nfp_2018: 0,
    usda_tag: 'CARTB',
    name: 'Carotene, beta',
    unit: 'Âµg',
  },
  {
    attr_id: 326,
    nfp_2018: 0,
    usda_tag: 'CHOCAL',
    name: 'Vitamin D3 (cholecalciferol)',
    unit: 'Âµg',
  },
  {
    attr_id: 421,
    nfp_2018: 0,
    usda_tag: 'CHOLN',
    name: 'Choline, total',
    unit: 'mg',
  },
  {
    attr_id: 334,
    nfp_2018: 0,
    usda_tag: 'CRYPX',
    name: 'Cryptoxanthin, beta',
    unit: 'Âµg',
  },
  {
    attr_id: 312,
    nfp_2018: 0,
    usda_tag: 'CU',
    name: 'Copper, Cu',
    unit: 'mg',
  },
  {
    attr_id: 507,
    nfp_2018: 0,
    usda_tag: 'CYS_G',
    name: 'Cystine',
    unit: 'g',
  },
  {
    attr_id: 268,
    nfp_2018: 0,
    usda_tag: 'ENERC_KJ',
    name: 'Energy',
    unit: 'kJ',
  },
  {
    attr_id: 325,
    nfp_2018: 0,
    usda_tag: 'ERGCAL',
    name: 'Vitamin D2 (ergocalciferol)',
    unit: 'Âµg',
  },
  {
    attr_id: 610,
    nfp_2018: 0,
    usda_tag: 'F10D0',
    name: '10:00',
    unit: 'g',
  },
  {
    attr_id: 611,
    nfp_2018: 0,
    usda_tag: 'F12D0',
    name: '12:00',
    unit: 'g',
  },
  {
    attr_id: 696,
    nfp_2018: 0,
    usda_tag: 'F13D0',
    name: '13:00',
    unit: 'g',
  },
  {
    attr_id: 612,
    nfp_2018: 0,
    usda_tag: 'F14D0',
    name: '14:00',
    unit: 'g',
  },
  {
    attr_id: 625,
    nfp_2018: 0,
    usda_tag: 'F14D1',
    name: '14:01',
    unit: 'g',
  },
  {
    attr_id: 652,
    nfp_2018: 0,
    usda_tag: 'F15D0',
    name: '15:00',
    unit: 'g',
  },
  {
    attr_id: 697,
    nfp_2018: 0,
    usda_tag: 'F15D1',
    name: '15:01',
    unit: 'g',
  },
  {
    attr_id: 613,
    nfp_2018: 0,
    usda_tag: 'F16D0',
    name: '16:00',
    unit: 'g',
  },
  {
    attr_id: 626,
    nfp_2018: 0,
    usda_tag: 'F16D1',
    name: '16:1 undifferentiated',
    unit: 'g',
  },
  {
    attr_id: 673,
    nfp_2018: 0,
    usda_tag: 'F16D1C',
    name: '16:1c',
    unit: 'g',
  },
  {
    attr_id: 662,
    nfp_2018: 0,
    usda_tag: 'F16D1T',
    name: '16:1 t',
    unit: 'g',
  },
  {
    attr_id: 653,
    nfp_2018: 0,
    usda_tag: 'F17D0',
    name: '17:00',
    unit: 'g',
  },
  {
    attr_id: 687,
    nfp_2018: 0,
    usda_tag: 'F17D1',
    name: '17:01',
    unit: 'g',
  },
  {
    attr_id: 614,
    nfp_2018: 0,
    usda_tag: 'F18D0',
    name: '18:00',
    unit: 'g',
  },
  {
    attr_id: 617,
    nfp_2018: 0,
    usda_tag: 'F18D1',
    name: '18:1 undifferentiated',
    unit: 'g',
  },
  {
    attr_id: 674,
    nfp_2018: 0,
    usda_tag: 'F18D1C',
    name: '18:1 c',
    unit: 'g',
  },
  {
    attr_id: 663,
    nfp_2018: 0,
    usda_tag: 'F18D1T',
    name: '18:1 t',
    unit: 'g',
  },
  {
    attr_id: 859,
    nfp_2018: 0,
    usda_tag: 'F18D1TN7',
    name: '18:1-11t (18:1t n-7)',
    unit: 'g',
  },
  {
    attr_id: 618,
    nfp_2018: 0,
    usda_tag: 'F18D2',
    name: '18:2 undifferentiated',
    unit: 'g',
  },
  {
    attr_id: 670,
    nfp_2018: 0,
    usda_tag: 'F18D2CLA',
    name: '18:2 CLAs',
    unit: 'g',
  },
  {
    attr_id: 675,
    nfp_2018: 0,
    usda_tag: 'F18D2CN6',
    name: '18:2 n-6 c,c',
    unit: 'g',
  },
  {
    attr_id: 669,
    nfp_2018: 0,
    usda_tag: 'F18D2TT',
    name: '18:2 t,t',
    unit: 'g',
  },
  {
    attr_id: 619,
    nfp_2018: 0,
    usda_tag: 'F18D3',
    name: '18:3 undifferentiated',
    unit: 'g',
  },
  {
    attr_id: 851,
    nfp_2018: 0,
    usda_tag: 'F18D3CN3',
    name: '18:3 n-3 c,c,c (ALA)',
    unit: 'g',
  },
  {
    attr_id: 685,
    nfp_2018: 0,
    usda_tag: 'F18D3CN6',
    name: '18:3 n-6 c,c,c',
    unit: 'g',
  },
  {
    attr_id: 627,
    nfp_2018: 0,
    usda_tag: 'F18D4',
    name: '18:04',
    unit: 'g',
  },
  {
    attr_id: 615,
    nfp_2018: 0,
    usda_tag: 'F20D0',
    name: '20:00',
    unit: 'g',
  },
  {
    attr_id: 628,
    nfp_2018: 0,
    usda_tag: 'F20D1',
    name: '20:01',
    unit: 'g',
  },
  {
    attr_id: 672,
    nfp_2018: 0,
    usda_tag: 'F20D2CN6',
    name: '20:2 n-6 c,c',
    unit: 'g',
  },
  {
    attr_id: 689,
    nfp_2018: 0,
    usda_tag: 'F20D3',
    name: '20:3 undifferentiated',
    unit: 'g',
  },
  {
    attr_id: 852,
    nfp_2018: 0,
    usda_tag: 'F20D3N3',
    name: '20:3 n-3',
    unit: 'g',
  },
  {
    attr_id: 853,
    nfp_2018: 0,
    usda_tag: 'F20D3N6',
    name: '20:3 n-6',
    unit: 'g',
  },
  {
    attr_id: 620,
    nfp_2018: 0,
    usda_tag: 'F20D4',
    name: '20:4 undifferentiated',
    unit: 'g',
  },
  {
    attr_id: 855,
    nfp_2018: 0,
    usda_tag: 'F20D4N6',
    name: '20:4 n-6',
    unit: 'g',
  },
  {
    attr_id: 629,
    nfp_2018: 0,
    usda_tag: 'F20D5',
    name: '20:5 n-3 (EPA)',
    unit: 'g',
  },
  {
    attr_id: 857,
    nfp_2018: 0,
    usda_tag: 'F21D5',
    name: '21:05',
    unit: 'g',
  },
  {
    attr_id: 624,
    nfp_2018: 0,
    usda_tag: 'F22D0',
    name: '22:00',
    unit: 'g',
  },
  {
    attr_id: 630,
    nfp_2018: 0,
    usda_tag: 'F22D1',
    name: '22:1 undifferentiated',
    unit: 'g',
  },
  {
    attr_id: 858,
    nfp_2018: 0,
    usda_tag: 'F22D4',
    name: '22:04',
    unit: 'g',
  },
  {
    attr_id: 631,
    nfp_2018: 0,
    usda_tag: 'F22D5',
    name: '22:5 n-3 (DPA)',
    unit: 'g',
  },
  {
    attr_id: 621,
    nfp_2018: 0,
    usda_tag: 'F22D6',
    name: '22:6 n-3 (DHA)',
    unit: 'g',
  },
  {
    attr_id: 654,
    nfp_2018: 0,
    usda_tag: 'F24D0',
    name: '24:00:00',
    unit: 'g',
  },
  {
    attr_id: 671,
    nfp_2018: 0,
    usda_tag: 'F24D1C',
    name: '24:1 c',
    unit: 'g',
  },
  {
    attr_id: 607,
    nfp_2018: 0,
    usda_tag: 'F4D0',
    name: '4:00',
    unit: 'g',
  },
  {
    attr_id: 608,
    nfp_2018: 0,
    usda_tag: 'F6D0',
    name: '6:00',
    unit: 'g',
  },
  {
    attr_id: 609,
    nfp_2018: 0,
    usda_tag: 'F8D0',
    name: '8:00',
    unit: 'g',
  },
  {
    attr_id: 645,
    nfp_2018: 0,
    usda_tag: 'FAMS',
    name: 'Fatty acids, total monounsaturated',
    unit: 'g',
  },
  {
    attr_id: 646,
    nfp_2018: 0,
    usda_tag: 'FAPU',
    name: 'Fatty acids, total polyunsaturated',
    unit: 'g',
  },
  {
    attr_id: 693,
    nfp_2018: 0,
    usda_tag: 'FATRNM',
    name: 'Fatty acids, total trans-monoenoic',
    unit: 'g',
  },
  {
    attr_id: 695,
    nfp_2018: 0,
    usda_tag: 'FATRNP',
    name: 'Fatty acids, total trans-polyenoic',
    unit: 'g',
  },
  {
    attr_id: 313,
    nfp_2018: 0,
    usda_tag: 'FLD',
    name: 'Fluoride',
    unit: 'Âµg',
  },
  {
    attr_id: 417,
    nfp_2018: 0,
    usda_tag: 'FOL',
    name: 'Folate',
    unit: 'Âµg',
  },
  {
    attr_id: 431,
    nfp_2018: 0,
    usda_tag: 'FOLAC',
    name: 'Folic acid',
    unit: 'Âµg',
  },
  {
    attr_id: 435,
    nfp_2018: 0,
    usda_tag: 'FOLDFE',
    name: 'Folate, DFE',
    unit: 'Âµg',
  },
  {
    attr_id: 432,
    nfp_2018: 0,
    usda_tag: 'FOLFD',
    name: 'Folate, food',
    unit: 'Âµg',
  },
  {
    attr_id: 212,
    nfp_2018: 0,
    usda_tag: 'FRUS',
    name: 'Fructose',
    unit: 'g',
  },
  {
    attr_id: 287,
    nfp_2018: 0,
    usda_tag: 'GALS',
    name: 'Galactose',
    unit: 'g',
  },
  {
    attr_id: 515,
    nfp_2018: 0,
    usda_tag: 'GLU_G',
    name: 'Glutamic acid',
    unit: 'g',
  },
  {
    attr_id: 211,
    nfp_2018: 0,
    usda_tag: 'GLUS',
    name: 'Glucose (dextrose)',
    unit: 'g',
  },
  {
    attr_id: 516,
    nfp_2018: 0,
    usda_tag: 'GLY_G',
    name: 'Glycine',
    unit: 'g',
  },
  {
    attr_id: 512,
    nfp_2018: 0,
    usda_tag: 'HISTN_G',
    name: 'Histidine',
    unit: 'g',
  },
  {
    attr_id: 521,
    nfp_2018: 0,
    usda_tag: 'HYP',
    name: 'Hydroxyproline',
    unit: 'g',
  },
  {
    attr_id: 503,
    nfp_2018: 0,
    usda_tag: 'ILE_G',
    name: 'Isoleucine',
    unit: 'g',
  },
  {
    attr_id: 213,
    nfp_2018: 0,
    usda_tag: 'LACS',
    name: 'Lactose',
    unit: 'g',
  },
  {
    attr_id: 504,
    nfp_2018: 0,
    usda_tag: 'LEU_G',
    name: 'Leucine',
    unit: 'g',
  },
  {
    attr_id: 338,
    nfp_2018: 0,
    usda_tag: 'LUT+ZEA',
    name: 'Lutein + zeaxanthin',
    unit: 'Âµg',
  },
  {
    attr_id: 337,
    nfp_2018: 0,
    usda_tag: 'LYCPN',
    name: 'Lycopene',
    unit: 'Âµg',
  },
  {
    attr_id: 505,
    nfp_2018: 0,
    usda_tag: 'LYS_G',
    name: 'Lysine',
    unit: 'g',
  },
  {
    attr_id: 214,
    nfp_2018: 0,
    usda_tag: 'MALS',
    name: 'Maltose',
    unit: 'g',
  },
  {
    attr_id: 506,
    nfp_2018: 0,
    usda_tag: 'MET_G',
    name: 'Methionine',
    unit: 'g',
  },
  {
    attr_id: 304,
    nfp_2018: 0,
    usda_tag: 'MG',
    name: 'Magnesium',
    unit: 'mg',
  },
  {
    attr_id: 428,
    nfp_2018: 0,
    usda_tag: 'MK4',
    name: 'Menaquinone-4',
    unit: 'Âµg',
  },
  {
    attr_id: 315,
    nfp_2018: 0,
    usda_tag: 'MN',
    name: 'Manganese',
    unit: 'mg',
  },
  {
    attr_id: 406,
    nfp_2018: 0,
    usda_tag: 'NIA',
    name: 'Niacin',
    unit: 'mg',
  },
  {
    attr_id: 573,
    nfp_2018: 0,
    usda_tag: NULL,
    name: 'Vitamin E, added',
    unit: 'mg',
  },
  {
    attr_id: 578,
    nfp_2018: 0,
    usda_tag: NULL,
    name: 'Vitamin B-12, added',
    unit: 'Âµg',
  },
  {
    attr_id: 257,
    nfp_2018: 0,
    usda_tag: NULL,
    name: 'Adjusted Protein',
    unit: 'g',
  },
  {
    attr_id: 664,
    nfp_2018: 0,
    usda_tag: NULL,
    name: '22:1 t',
    unit: 'g',
  },
  {
    attr_id: 676,
    nfp_2018: 0,
    usda_tag: NULL,
    name: '22:1 c',
    unit: 'g',
  },
  {
    attr_id: 856,
    nfp_2018: 0,
    usda_tag: NULL,
    name: '18:3i',
    unit: 'g',
  },
  {
    attr_id: 665,
    nfp_2018: 0,
    usda_tag: NULL,
    name: '18:2 t not further defined',
    unit: 'g',
  },
  {
    attr_id: 666,
    nfp_2018: 0,
    usda_tag: NULL,
    name: '18:2 i',
    unit: 'g',
  },
  {
    attr_id: 305,
    nfp_2018: 0,
    usda_tag: 'P',
    name: 'Phosphorus',
    unit: 'mg',
  },
  {
    attr_id: 410,
    nfp_2018: 0,
    usda_tag: 'PANTAC',
    name: 'Pantothenic acid',
    unit: 'mg',
  },
  {
    attr_id: 508,
    nfp_2018: 0,
    usda_tag: 'PHE_G',
    name: 'Phenylalanine',
    unit: 'g',
  },
  {
    attr_id: 636,
    nfp_2018: 0,
    usda_tag: 'PHYSTR',
    name: 'Phytosterols',
    unit: 'mg',
  },
  {
    attr_id: 517,
    nfp_2018: 0,
    usda_tag: 'PRO_G',
    name: 'Proline',
    unit: 'g',
  },
  {
    attr_id: 319,
    nfp_2018: 0,
    usda_tag: 'RETOL',
    name: 'Retinol',
    unit: 'Âµg',
  },
  {
    attr_id: 405,
    nfp_2018: 0,
    usda_tag: 'RIBF',
    name: 'Riboflavin',
    unit: 'mg',
  },
  {
    attr_id: 317,
    nfp_2018: 0,
    usda_tag: 'SE',
    name: 'Selenium, Se',
    unit: 'Âµg',
  },
  {
    attr_id: 518,
    nfp_2018: 0,
    usda_tag: 'SER_G',
    name: 'Serine',
    unit: 'g',
  },
  {
    attr_id: 641,
    nfp_2018: 0,
    usda_tag: 'SITSTR',
    name: 'Beta-sitosterol',
    unit: 'mg',
  },
  {
    attr_id: 209,
    nfp_2018: 0,
    usda_tag: 'STARCH',
    name: 'Starch',
    unit: 'g',
  },
  {
    attr_id: 638,
    nfp_2018: 0,
    usda_tag: 'STID7',
    name: 'Stigmasterol',
    unit: 'mg',
  },
  {
    attr_id: 210,
    nfp_2018: 0,
    usda_tag: 'SUCS',
    name: 'Sucrose',
    unit: 'g',
  },
  {
    attr_id: 263,
    nfp_2018: 0,
    usda_tag: 'THEBRN',
    name: 'Theobromine',
    unit: 'mg',
  },
  {
    attr_id: 404,
    nfp_2018: 0,
    usda_tag: 'THIA',
    name: 'Thiamin',
    unit: 'mg',
  },
  {
    attr_id: 502,
    nfp_2018: 0,
    usda_tag: 'THR_G',
    name: 'Threonine',
    unit: 'g',
  },
  {
    attr_id: 323,
    nfp_2018: 0,
    usda_tag: 'TOCPHA',
    name: 'Vitamin E (alpha-tocopherol)',
    unit: 'mg',
  },
  {
    attr_id: 341,
    nfp_2018: 0,
    usda_tag: 'TOCPHB',
    name: 'Tocopherol, beta',
    unit: 'mg',
  },
  {
    attr_id: 343,
    nfp_2018: 0,
    usda_tag: 'TOCPHD',
    name: 'Tocopherol, delta',
    unit: 'mg',
  },
  {
    attr_id: 342,
    nfp_2018: 0,
    usda_tag: 'TOCPHG',
    name: 'Tocopherol, gamma',
    unit: 'mg',
  },
  {
    attr_id: 501,
    nfp_2018: 0,
    usda_tag: 'TRP_G',
    name: 'Tryptophan',
    unit: 'g',
  },
  {
    attr_id: 509,
    nfp_2018: 0,
    usda_tag: 'TYR_G',
    name: 'Tyrosine',
    unit: 'g',
  },
  {
    attr_id: 510,
    nfp_2018: 0,
    usda_tag: 'VAL_G',
    name: 'Valine',
    unit: 'g',
  },
  {
    attr_id: 318,
    nfp_2018: 0,
    usda_tag: 'VITA_IU',
    name: 'Vitamin A, IU',
    unit: 'IU',
  },
  {
    attr_id: 320,
    nfp_2018: 0,
    usda_tag: 'VITA_RAE',
    name: 'Vitamin A, RAE',
    unit: 'Âµg',
  },
  {
    attr_id: 418,
    nfp_2018: 0,
    usda_tag: 'VITB12',
    name: 'Vitamin B-12',
    unit: 'Âµg',
  },
  {
    attr_id: 415,
    nfp_2018: 0,
    usda_tag: 'VITB6A',
    name: 'Vitamin B-6',
    unit: 'mg',
  },
  {
    attr_id: 401,
    nfp_2018: 0,
    usda_tag: 'VITC',
    name: 'Vitamin C, total ascorbic acid',
    unit: 'mg',
  },
  {
    attr_id: 328,
    nfp_2018: 0,
    usda_tag: 'VITD',
    name: 'Vitamin D (D2 + D3)',
    unit: 'Âµg',
  },
  {
    attr_id: 430,
    nfp_2018: 0,
    usda_tag: 'VITK1',
    name: 'Vitamin K (phylloquinone)',
    unit: 'Âµg',
  },
  {
    attr_id: 429,
    nfp_2018: 0,
    usda_tag: 'VITK1D',
    name: 'Dihydrophylloquinone',
    unit: 'Âµg',
  },
  {
    attr_id: 255,
    nfp_2018: 0,
    usda_tag: 'WATER',
    name: 'Water',
    unit: 'g',
  },
  {
    attr_id: 309,
    nfp_2018: 0,
    usda_tag: 'ZN',
    name: 'Zinc, Zn',
    unit: 'mg',
  },
]

export default data
