export const RESET_BASKET = "RESET_BASKET"
export const EDIT_BASKET = "EDIT_BASKET"

export const ADD_BASKET_ITEM = "ADD_BASKET_ITEM"
export const DELETE_BASKET_ITEM = "DELETE_BASKET_ITEM"
export const EDIT_BASKET_ITEM = "EDIT_BASKET_ITEM"


export const ADD_ITEMS_TO_BASKET = "ADD_ITEMS_TO_BASKET"
